id: 8202359c42fe4434a4539f7a07f97ad0
initial_creation_type: ocr
source_metadata:
  volumes:
    fedf802c7e70486483930232f6be6bc5:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: སྟོང་པ་ཉིད་བདུན་ཅུ་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
